Add README file to args demo
DavidSpickett/ARMMultiTasking pull request #17
Opened 2020-12-29 11:51 UTC by OscarShiang

Make some description of the args demo.

2021-01-06 18:44 UTC, DavidSpickett requested changes
You should add a link to this file in the docs/demos file.

2021-01-06 18:44 UTC, DavidSpickett commented on demos/args/README.md
> +`thread_start` is the starting point of every thread. When the scheduler chooses a thread to run, it loads the arguments from the thread structure and runs the worker routine.
This implies that the scheduler does the loading. I'd say:
"`thread_start` is the starting point of every thread, it loads the arguments from the thread structure and runs the worker routine."

2021-01-06 18:44 UTC, DavidSpickett commented on demos/args/README.md
> +* `2` -> `start`
This would make more sense if we reverse the order. Like:

We pass the following arguments to `printer`:
* `repeat` = `3`

2021-01-06 18:44 UTC, DavidSpickett commented on demos/args/README.md
> +When `printer` finished its work, `subprinter` has been yielded and its arguments have been initialized as below:
I'm not sure you mean by "has been yielded".

Maybe:
"When `printer` finishes its work, the next thread will be`subprinter`."

2021-01-06 18:44 UTC, DavidSpickett commented on demos/args/README.md
> +* `2` -> `offset`
Same comment as above

2021-01-07 01:44 UTC, OscarShiang commented
OK, I have fixed them.

2021-01-09 11:43 UTC, DavidSpickett approved these changes

2021-01-09 11:43 UTC, merged