Create README file for mutex demo
DavidSpickett/ARMMultiTasking pull request #18
Opened 2021-01-17 12:28 UTC by OscarShiang

Add description of the mutex demo.

2021-01-20 19:15 UTC, DavidSpickett requested changes

2021-01-20 19:15 UTC, DavidSpickett commented on demos/mutexes/README.md
> +When a thread finishes its operation to the shared variables protected by the mutex, we use this function to release the lock.
"operations on the shared variables"

2021-01-20 19:15 UTC, DavidSpickett commented on demos/mutexes/README.md
> +In the beginning, we initialize two threads to do `thread_worker` routine. The routine is to copy a given string to the global array called `buf`.
"to do the `thread worker` routine"
"The routine copies a given string"

2021-01-20 19:15 UTC, DavidSpickett commented on demos/mutexes/README.md
> +Since thread 1 has been created earlier, when `setup()` ends, the scheduler chooses it to yield. After entering `thread_worker()` function, thread 1 acquires the lock and starts to copy `"dog"` into
"chooses it to run first."

2021-01-20 19:15 UTC, DavidSpickett commented on demos/mutexes/README.md
> +Since thread 1 locked the mutex before, thread 2 can not enter the section but need to yield and wait.
"but must yield and wait"

2021-01-20 19:15 UTC, DavidSpickett commented on demos/mutexes/README.md
> +Until thread 1 ends its copying, it releases the mutex. Then thread 2 can enter the section and copy `"cat"` to `buf`.
"Once thread 1 ends its copying, it prints `buf` and releases the mutex."

"Then thread 2 can acquire the lock"

2021-01-20 19:15 UTC, DavidSpickett commented on demos/mutexes/README.md
> +Finally, when thread 2 prints out its result of copying, the demo ends.
"Finally thread 2 prints the result of its copying, and the demo ends.

2021-01-21 04:08 UTC, OscarShiang commented
I have fixed in the new commit.

2021-01-22 16:37 UTC, DavidSpickett approved these changes
LGTM, thanks!

2021-01-22 16:37 UTC, merged