Describe the file demo in the README
DavidSpickett/ARMMultiTasking pull request #22
Opened 2021-02-08 07:51 UTC by OscarShiang

Create README file in demos/file to explain concepts of the file demo.

2021-02-08 17:00 UTC, DavidSpickett requested changes

2021-02-08 17:00 UTC, DavidSpickett commented on docs/demos.md
> +| fiber                                                       | User space threading.                                                             |
Looks like an accidental edit, not that I can tell from the diff what changed here.

2021-02-08 17:00 UTC, DavidSpickett commented on docs/demos.md
> +| [file](../demos/file/READM.md)                              | Read from a file.                                                                 |
README.md (missing the last E)

2021-02-08 17:00 UTC, DavidSpickett commented on demos/file/README.md
> +In AMT, the permissions we provide are `O_RDONLY` and `O_WRONLY`.
Although these are kinda permissions, https://man7.org/linux/man-pages/man2/open.2.html refers to them as "access modes" so I'd rather use that term.

2021-02-08 17:00 UTC, DavidSpickett commented on demos/file/README.md
> +If the operation succeeds, the return value will be `0`. If the operation failed, the return value will be `-1`
you can remove the first comma

"If the operation succeeds the return value will be `0`."

2021-02-08 17:00 UTC, DavidSpickett commented on demos/file/README.md
> +If we can open a file, the return value will be nonzero. If we can not open a file, the value will be set to `-1`.
"open the file" makes more sense here

2021-02-08 17:00 UTC, DavidSpickett commented on demos/file/README.md
> +The return value will be set to `0` if the operation successes. If it fails, the value will be `-1`.
"if the operation succeeds"

2021-02-08 17:00 UTC, DavidSpickett commented on demos/file/README.md
> +The second case tries to open a file that is not existing in the path. As a result, the returned file descriptor must be `-1`, which indicates the failure of open.
"that does not exist."

2021-02-08 17:00 UTC, DavidSpickett commented on demos/file/README.md
> +For the third case, we test the `write()` by writing a string into a temporary file and verify the operation by justifying the number of bytes we just wrote. After that, we close the file descriptor
"justifying" isn't the word here.

Perhaps:
"and asserting that `write` returned the number of bytes we tried to write."

2021-02-08 17:00 UTC, DavidSpickett commented on demos/file/README.md
> +The return value will be the number of bytes written on success.
This leaves out the failure value, which is -1 like the rest. (https://man7.org/linux/man-pages/man2/write.2.html)

2021-02-09 04:32 UTC, OscarShiang commented on docs/demos.md
> +| fiber                                                       | User space threading.                                                             |
Sorry about that. It seems my vim automatically add a newline at the end of the file.

2021-02-09 04:34 UTC, OscarShiang commented
OK, I have updated the commit.

2021-02-09 19:47 UTC, DavidSpickett approved these changes
LGTM

2021-02-09 19:47 UTC, merged