Create an option for enable/disable semihosting
DavidSpickett/ARMMultiTasking pull request #23
Opened 2021-03-22 07:46 UTC by OscarShiang

In this patch, I add an new option in CMakeLists file to control whether
the semihosting feature should be turned on or off.

If semihosting has been disabled, the exit syscall will print out
"Exiting kernel" and hang in a while-loop. waiting the user to exit
manually.

Semihosting feature may not be provided by some devices. (e.g. Raspberry Pi)

I am currently working on porting AMT onto Raspberry Pi 4B, running 
semihosting may cause the board halted. So I think we should provide an extra
setting to control this feature.

2021-03-22 08:56 UTC, jserv requested changes
You can simplify the subject of this pull request to "Make Arm semihosting support optional."

2021-03-22 09:04 UTC, OscarShiang commented
OK, I will do it.

2021-03-25 16:28 UTC, DavidSpickett requested changes

2021-03-25 16:28 UTC, DavidSpickett commented on CMakeLists.txt
> +option( SEMIHOSTING "Enable semihosting." ON )
If this is going to be set automatically per board (which is fine) it should be done like STACK_SIZE etc. Using set.
(option makes it seem like you can do cmake ... -DSEMIHOSTING=OFF, but you can't)

Also when you do that, you can remove the ON values for the current boards, just set it once, and over in your rpi fork just set OFF for that one.

2021-03-25 16:28 UTC, DavidSpickett commented on src/hw/arm_common/port.c
> +  return -1;
Please mark the parameters used here. Like:
```
(void)operation; (void)parameters;
```

2021-03-25 16:41 UTC, DavidSpickett commented on src/hw/arm_common/port.c
> +  return -1;
I'm going to enable -Wunused-params to catch this sort of thing.

2021-03-26 01:33 UTC, OscarShiang commented
OK, I have force-pushed the commit.

2021-03-27 10:07 UTC, DavidSpickett approved these changes
LGTM

2021-03-27 10:07 UTC, merged